In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("AQI_data.csv")
df.head()

,AQSID,SiteName,Status,EPARegion,Latitude,Longitude,Elevation,GMTOffset,CountryCode,StateName,...,OZONE,OZONE_Unit,NO2,NO2_Unit,CO,CO_Unit,SO2,SO2_Unit,PM10,PM10_Unit
0,250250002,BOSTON-KENMORE,Active,R1,42.348900,-71.097702,0.0,-5.0,US,MA,...,8.0,UG/M3,0.0,PPB,NaN,NaN,6.0,PPB,NaN,NaN
1,250250044,Boston-Von Hillern,Active,R1,42.325197,-71.056056,4.0,-5.0,US,MA,...,7.0,UG/M3,NaN,NaN,NaN,NaN,7.0,PPB,NaN,NaN
2,250250042,Boston - Roxbury,Active,R1,42.329399,-71.082497,0.0,-5.0,US,MA,...,7.0,UG/M3,0.0,PPB,42.0,PPB,4.0,PPB,NaN,NaN
3,250250043,Boston - North End,Inactive,R1,42.363100,-71.054200,0.0,-5.0,US,MA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,250250041,Boston - Long Island,Inactive,R1,42.317200,-70.966700,0.0,-5.0,US,MA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# drop rows with value "Sitename" == "Chelsea HP"
df = df[df['SiteName'] != 'Chelsea HP']
df = df[df['Status'] != 'Inactive']

# drop column PM10_AQI, PM10, PM10_Unit (all null values)
df = df.drop(['PM10_AQI', 'PM10', 'PM10_Unit', 'PM10_Measured'], axis=1)

# drop colums that is not useful for analysis
df = df.drop(["StateName", "CountryCode", "DataSource", "ReportingArea_PipeDelimited", "ValidTime", "GMTOffset", "Elevation", "Longitude", "Latitude", "EPARegion", "AQSID", "Status"], axis=1)


df.head()

,SiteName,ValidDate,OZONE_AQI,PM25_AQI,NO2_AQI,OZONE_Measured,PM25_Measured,NO2_Measured,PM25,PM25_Unit,OZONE,OZONE_Unit,NO2,NO2_Unit,CO,CO_Unit,SO2,SO2_Unit
0,BOSTON-KENMORE,04/01/21,NaN,34.0,6.0,0,1,1,NaN,NaN,8.0,UG/M3,0.0,PPB,NaN,NaN,6.0,PPB
1,Boston-Von Hillern,04/01/21,NaN,28.0,7.0,0,1,1,NaN,NaN,7.0,UG/M3,NaN,NaN,NaN,NaN,7.0,PPB
2,Boston - Roxbury,04/01/21,38.0,23.0,4.0,1,1,1,0.21,PPM,7.0,UG/M3,0.0,PPB,42.0,PPB,4.0,PPB
5,BOSTON-KENMORE,04/02/21,NaN,12.0,4.0,0,1,1,NaN,NaN,3.0,UG/M3,0.0,PPB,NaN,NaN,4.0,PPB
6,Boston-Von Hillern,04/02/21,NaN,28.0,9.0,0,1,1,0.04,PPM,7.0,UG/M3,NaN,NaN,NaN,NaN,10.0,PPB

In [4]:
features_interested = ['SiteName', 'ValidDate','OZONE_AQI','PM25_AQI', 'NO2_AQI']
data = df[features_interested]

# # fill null value with mean value
data['OZONE_AQI'].fillna(data['OZONE_AQI'].mean(), inplace=True)
data['PM25_AQI'].fillna(data['PM25_AQI'].mean(), inplace=True)
data['NO2_AQI'].fillna(data['NO2_AQI'].mean(), inplace=True)

data.head()

/var/folders/37/5r4fjllx115gd2m3kmqy_02m0000gn/T/ipykernel_73368/4278286263.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['OZONE_AQI'].fillna(data['OZONE_AQI'].mean(), inplace=True)
/var/folders/37/5r4fjllx115gd2m3kmqy_02m0000gn/T/ipykernel_73368/4278286263.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['PM25_AQI'].fillna(data['PM25_AQI'].mean(), inplace=True)
/var/folders/37/5r4fjllx115gd2m3kmqy_02m0000gn/T/ipykernel_73368/4278286263.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['NO2_AQI'].fillna(data['NO2_AQI'].mean(), inplace=True)

             SiteName ValidDate  OZONE_AQI  PM25_AQI  NO2_AQI
0      BOSTON-KENMORE  04/01/21  25.058496      34.0      6.0
1  Boston-Von Hillern  04/01/21  25.058496      28.0      7.0
2    Boston - Roxbury  04/01/21  38.000000      23.0      4.0
5      BOSTON-KENMORE  04/02/21  25.058496      12.0      4.0
6  Boston-Von Hillern  04/02/21  25.058496      28.0      9.0

In [7]:
# Sort the DataFrame by the 'ValidDate' column in ascending order
data['ValidDate'] = pd.to_datetime(data['ValidDate'])
data.sort_values(by='ValidDate', ascending=True, inplace=True)

# If you want to reset the index after sorting
data.reset_index(drop=True, inplace=True)

data

/var/folders/37/5r4fjllx115gd2m3kmqy_02m0000gn/T/ipykernel_73368/1091821723.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ValidDate'] = pd.to_datetime(data['ValidDate'])
/var/folders/37/5r4fjllx115gd2m3kmqy_02m0000gn/T/ipykernel_73368/1091821723.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.sort_values(by='ValidDate', ascending=True, inplace=True)

                SiteName  ValidDate  OZONE_AQI  PM25_AQI  NO2_AQI
0     Boston-Von Hillern 2021-01-01  25.058496      18.0     11.0
1       Boston - Roxbury 2021-01-01  15.000000      14.0     13.0
2         BOSTON-KENMORE 2021-01-01  25.058496      22.0      5.0
3       Boston - Roxbury 2021-01-02  15.000000      28.0     18.0
4     Boston-Von Hillern 2021-01-02  25.058496      47.0     17.0
...                  ...        ...        ...       ...      ...
1088    Boston - Roxbury 2021-12-30  12.000000      33.0     15.0
1089  Boston-Von Hillern 2021-12-30  25.058496      32.0     10.0
1090      BOSTON-KENMORE 2021-12-31  25.058496      45.0     18.0
1091  Boston-Von Hillern 2021-12-31  25.058496      44.0     21.0
1092    Boston - Roxbury 2021-12-31   4.000000      40.0     22.0

[1093 rows x 5 columns]

In [9]:
# aggregate data by SiteName
agg_data = data.groupby('SiteName').mean()
agg_data

,ValidDate,OZONE_AQI,PM25_AQI,NO2_AQI
SiteName,,,,
BOSTON-KENMORE,2021-07-02 05:32:18.461538560,25.058496,29.604353,11.345447
Boston - Roxbury,2021-07-02 00:00:00.000000000,25.058496,22.136913,11.080978
Boston-Von Hillern,2021-07-02 05:32:18.461538560,25.058496,32.269078,12.353492

In [16]:
neighborhood_insterested = ["Allston", "Back Bay", "Bay Village", "Brighton", "Charlestown", "Dorchester", "East Boston", "Fenway", "Harbor Islands", "Hyde Park", "Jamaica Plain", "Leather District", "Longwood Medical Area", "Mattapan", "Mission Hill", "North End", "Roslindale", "Roxbury", "South Boston", "South Boston Waterfront", "South End", "West End", "West Roxbury"]
new_df = pd.DataFrame({"Name": neighborhood_insterested})
new_df.head()

          Name
0      Allston
1     Back Bay
2  Bay Village
3     Brighton
4  Charlestown

(longitutde, latitude) for different neighborhood in Boston

In [19]:
boston_kenmore = (42.348900, -71.097702)
boston_vonhillern = (42.325197,	-71.056056) 
boston_roxbury = (42.329399, -71.082497)
Allston = (42.3555, -71.1328)
Back_Bay = (42.3495, -71.0795)
Bay_Village = (42.3487, -71.0694)
Brighton = (42.3489, -71.1605)
Charlestown = (42.3787, -71.0616)
Dorchester = (42.2995, -71.0649)
East_Boston = (42.3800, -71.0254)
Fenway = (42.3468, -71.0923)
Harbor_Islands = (42.3216, -70.9649)
Hyde_Park = (42.2557, -71.1256)
Jamaica_Plain = (42.3132, -71.1141)
Leather_District = (42.3506, -71.0574)
Longwood_Medical_Area = (42.3389, -71.1072)
Mattapan = (42.2772, -71.0935)
Mission_Hill = (42.3299, -71.1060)
North_End = (42.3652, -71.0555)
Roslindale = (42.2832, -71.1265)
Roxbury = (42.3126, -71.0899)
South_Boston = (42.3355, -71.0457)
South_Boston_Waterfront = (42.3463, -71.0421)
South_End = (42.3407, -71.0706)
West_End = (42.3652, -71.0641)
West_Roxbury = (42.2782, -71.1600)

site_loc = [boston_kenmore, boston_vonhillern, boston_roxbury]
neighborhood_loc = [Allston, Back_Bay, Bay_Village, Brighton, Charlestown, Dorchester, East_Boston, Fenway, Harbor_Islands, Hyde_Park, Jamaica_Plain, Leather_District, Longwood_Medical_Area, Mattapan, Mission_Hill, North_End, Roslindale, Roxbury, South_Boston, South_Boston_Waterfront, South_End, West_End, West_Roxbury]

In [22]:
# assign site name to each neighborhood based on distance to each site
def find_site_name(lat, lon):
    min_dis = 1000000

    for i in range(len(site_loc)):
        dis = ((lat - site_loc[i][0])**2 + (lon - site_loc[i][1])**2) ** 0.5
        if dis < min_dis:
            min_dis = dis
            site_name = agg_data.index[i]
    
    return site_name

assign_site_name = []
for (lat, lon) in neighborhood_loc:
    site_name = find_site_name(lat, lon)
    assign_site_name.append(site_name)

new_df['SiteName'] = assign_site_name
new_df

                       Name            SiteName
0                   Allston      BOSTON-KENMORE
1                  Back Bay      BOSTON-KENMORE
2               Bay Village  Boston-Von Hillern
3                  Brighton      BOSTON-KENMORE
4               Charlestown      BOSTON-KENMORE
5                Dorchester    Boston - Roxbury
6               East Boston    Boston - Roxbury
7                    Fenway      BOSTON-KENMORE
8            Harbor Islands    Boston - Roxbury
9                 Hyde Park  Boston-Von Hillern
10            Jamaica Plain  Boston-Von Hillern
11         Leather District    Boston - Roxbury
12    Longwood Medical Area      BOSTON-KENMORE
13                 Mattapan  Boston-Von Hillern
14             Mission Hill      BOSTON-KENMORE
15                North End    Boston - Roxbury
16               Roslindale  Boston-Von Hillern
17                  Roxbury  Boston-Von Hillern
18             South Boston    Boston - Roxbury
19  South Boston Waterfront    Boston - Roxbury
20                South End  Boston-Von Hillern
21                 West End      BOSTON-KENMORE
22             West Roxbury  Boston-Von Hillern

In [23]:
# assign the corresponding AQI to each neighborhood
def find_AQI(site_name, pollutant):
    return agg_data.loc[site_name][pollutant]

OZONE_AQI = []
PM25_AQI = []
NO2_AQI = []
for site_name in assign_site_name:
    OZONE_AQI.append(find_AQI(site_name, 'OZONE_AQI'))
    PM25_AQI.append(find_AQI(site_name, 'PM25_AQI'))
    NO2_AQI.append(find_AQI(site_name, 'NO2_AQI'))

new_df['OZONE_AQI'] = OZONE_AQI
new_df['PM25_AQI'] = PM25_AQI
new_df['NO2_AQI'] = NO2_AQI
new_df

,Name,SiteName,OZONE_AQI,PM25_AQI,NO2_AQI
0,Allston,BOSTON-KENMORE,25.058496,29.604353,11.345447
1,Back Bay,BOSTON-KENMORE,25.058496,29.604353,11.345447
2,Bay Village,Boston-Von Hillern,25.058496,32.269078,12.353492
3,Brighton,BOSTON-KENMORE,25.058496,29.604353,11.345447
4,Charlestown,BOSTON-KENMORE,25.058496,29.604353,11.345447
5,Dorchester,Boston - Roxbury,25.058496,22.136913,11.080978
6,East Boston,Boston - Roxbury,25.058496,22.136913,11.080978
7,Fenway,BOSTON-KENMORE,25.058496,29.604353,11.345447
8,Harbor Islands,Boston - Roxbury,25.058496,22.136913,11.080978
9,Hyde Park,Boston-Von Hillern,25.058496,32.269078,12.353492
10,Jamaica Plain,Boston-Von Hillern,25.058496,32.269078,12.353492
11,Leather District,Boston - Roxbury,25.058496,22.136913,11.080978
12,Longwood Medical Area,BOSTON-KENMORE,25.058496,29.604353,11.345447
13,Mattapan,Boston-Von Hillern,25.058496,32.269078,12.353492
14,Mission Hill,BOSTON-KENMORE,25.058496,29.604353,11.345447
15,North End,Boston - Roxbury,25.058496,22.136913,11.080978
16,Roslindale,Boston-Von Hillern,25.058496,32.269078,12.353492
17,Roxbury,Boston-Von Hillern,25.058496,32.269078,12.353492
18,South Boston,Boston - Roxbury,25.058496,22.136913,11.080978
19,South Boston Waterfront,Boston - Roxbury,25.058496,22.136913,11.080978
20,South End,Boston-Von Hillern,25.058496,32.269078,12.353492
21,West End,BOSTON-KENMORE,25.058496,29.604353,11.345447
22,West Roxbury,Boston-Von Hillern,25.058496,32.269078,12.353492